version: '3.8'
services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: billiards_postgres
    environment:
      POSTGRES_DB: billiards_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: billiards_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@billiards.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # Redis for caching and sessions (optional but recommended)
  redis:
    image: redis:7-alpine
    container_name: billiards_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # NGINX Reverse Proxy & Load Balancer
  nginx:
    image: nginx:alpine
    container_name: billiards_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped

  # Your Node.js Hello World App
  app:
    build: .
    container_name: billiards_app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=billiards_platform
      - DB_USER=postgres
      - DB_PASSWORD=password123
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - DATABASE_URL=postgresql://postgres:password123@postgres:5432/billiards_platform
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
