apiVersion: apps/v1
kind: Deployment
metadata:
  name: billiards-backend
  namespace: billiards-backend
  labels:
    app: billiards-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: billiards-backend
  template:
    metadata:
      labels:
        app: billiards-backend
    spec:
      containers:
      - name: billiards-backend
        image: billiards-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: billiards-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: billiards-config
              key: PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: billiards-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: billiards-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: billiards-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: billiards-config
              key: DB_USER
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: billiards-config
              key: REDIS_URL
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: billiards-secrets
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: billiards-secrets
              key: JWT_SECRET
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: billiards-secrets
              key: DATABASE_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
