apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: doppler-secret-store
  namespace: billiards-backend
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token
            key: doppler-token
      project: billiards-backend
      config: production
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: billiards-external-secrets
  namespace: billiards-backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-secret-store
    kind: SecretStore
  target:
    name: billiards-secrets
    creationPolicy: Owner
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: DB_PASSWORD
  - secretKey: JWT_SECRET
    remoteRef:
      key: JWT_SECRET
  - secretKey: DATABASE_URL
    remoteRef:
      key: DATABASE_URL
