apiVersion: v1
kind: Secret
metadata:
  name: billiards-secrets
  namespace: billiards-backend
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  DB_PASSWORD: cGFzc3dvcmQxMjM=  # password123
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQta2V5LWNoYW5nZS10aGlzLWluLXByb2R1Y3Rpb24=  # your-super-secret-key-change-this-in-production
  DATABASE_URL: cG9zdGdyZXNxbDovL2JpbGxpYXJkc191c2VyOnBhc3N3b3JkMTIzQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9iaWxsaWFyZHNfcGxhdGZvcm0=  # postgresql://billiards_user:password123@postgres-service:5432/billiards_platform
